### ISSUE TITLE
Figure out design on browsers narrower than 1100px

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#135]
Currently our "Top Sites" wraps at around 1100-1101px and causes the 6th site to wrap onto the following line and then everything goes a bit sideways.

We should come up with a solution of what should happen on smaller browsers. Should the Top Sites wrap onto a second line? Just hide any items that don't fit and do some `overflow:hidden` magic.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13127565/df339250-d584-11e5-99b6-d6fb33da0179.png)
**Figure 1:** Current behavior at 1100px width on the **style-tweaks** branch.

---

#### Workaround:

Set an explicit height on the "Top Sites" container and hide any overflow:

![new_tab](https://cloud.githubusercontent.com/assets/557895/13127631/46b0783a-d585-11e5-86c0-6fc28226b5bd.png)
**Figure 2:** Some inline CSS hackery with `overflow: hidden; max-height: 114px;`:

```html
<div style="overflow: hidden; max-height: 114px;" class="tiles-wrapper">
```

**Comment by pdehaan** [comment]
Actually, I guess the proper way to solve the overflow would be to tweak TopSites.scss:
```scss
.top-sites {
  .tiles-wrapper {
    margin-right: -20px;
    max-height: $tile-height + $tile-gutter-v;
    overflow: hidden;
    text-align: center;
  }

  ...
}
```
