### ISSUE TITLE
Add some Sass linting?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#75]
I have a local, crude lint set up using https://github.com/sasstools/sass-lint and have it returning about 74 warnings and 4 errors (mostly sorting violations and nit-picky formatting)...

### .sass-lint.yml
```yml
options:
  merge-default-rules: true

files:
  include: 'content-src/**/*.scss'


rules:
  extends-before-declarations: 2
  extends-before-mixins: 2
  hex-notation: [2, {style: uppercase}]
  indentation: [2, {size: 2}]
  leading-zero: [2, {include: true}]
  mixins-before-declarations: [2, {exclude: [breakpoint, mq]}]
  nesting-depth: [2, {max-depth: 4}]
  no-debug: 1
  no-ids: 1
  no-important: 1
  no-warn: 1
  placeholder-in-extend: 2
  property-sort-order: [1, {order: [display, margin], ignore-custom-properties: true}]
```

After you do an `npm i sass-lint` locally, you can run the following command to see the lint results:
```sh
$ ./node_modules/.bin/sass-lint -v -q #or just `sass-lint -v -q` in the package.json scripts section
```
