### ISSUE TITLE
Add a link hover state to the spotlight

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#98]
Currently the [Top Sites](https://github.com/mozilla/activity-streams/blob/3a42234353fb93845e7966ed66da6aed1b9a0731/content-src/components/TopSites/TopSites.scss#L47-L50) have a hover state, and the [Activity Feed](https://github.com/mozilla/activity-streams/blob/3a42234353fb93845e7966ed66da6aed1b9a0731/content-src/main.scss#L25-L27) links have a slight hover (via the global `a:hover` selector), but there doesn't seem to be any hover state for Spotlight results.

I fixed it by adding a `&:hover` state to the `.spotlight-title` selector:
```scss
  .spotlight-title {
    margin: 0 0 5px 0;

    a {
      color: $dark-grey;

      &:hover {
        color: $light-grey;
      }
    }
  }
```
